# Generated by Django 4.2 on 2023-05-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallSection',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
