# Generated by Django 4.2 on 2023-05-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bouldering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=200)),
                ('grade', models.IntegerField(default=1)),
                ('wall_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouldering.wallsection')),
            ],
        ),
    ]
